version: "2.2"

services:
  mongo:
    image: mongo:5.0
    container_name: admin_mongo
    #    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db:rw
      - ./init:/docker-entrypoint-initdb.d

  auth:
    image: wi4er/charon:0.0.3
    container_name: admin_auth
    environment:
      DB_HOST: mongo
      DB_USER: auth
      DB_PASSWORD: example
      DB_NAME: auth
      SECRET: "hello world!"
      ACCESS_TOKEN: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiYWRtaW4iOnRydWUsImlhdCI6MTY1NDgyODkwNH0.Jvkk-wfyzdUgANBI1GyoFZ-FpkDnlst6ICAGSxv3iCg"
      USER_HOST: user
      USER_PORT: 8080
    links:
      - mongo
    ports:
      - "8083:8080"

  user:
    image: wi4er/groot:0.11.1
    container_name: admin_user
    environment:
      DB_HOST: mongo
      DB_USER: user
      DB_PASSWORD: example
      DB_NAME: user
      SECRET: "hello world!"
      CACHE_HOST: cache
    links:
      - mongo
      - cache
    ports:
      - "8081:8080"

  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data/
